version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python=3.9 /usr/local/share/virtualenvs/tap-doubleclick-campaign-manager
            source /usr/local/share/virtualenvs/tap-doubleclick-campaign-manager/bin/activate
            uv pip install -U pip setuptools
            uv pip install .[dev]
      - run:
          when: always
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-doubleclick-campaign-manager/bin/activate
            pytest tests/unittests
      - slack/notify-on-failure:
          only_for_branches: master
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
